#!/bin/bash

function start {
		node apps/server/ldap-auth/server.js& >/dev/null 
		echo $! > ldap.pid
		node apps/server/app-serv/server.js& >/dev/null
		echo $! > app-serv.pid
		node server.js& >/dev/null
		echo $! > router.pid
		}

./stop && start && echo 'started' && exit 0;




